sudo: required
services:
  - docker

cache:
  directories:
    - .cabal-sandbox.docker

before_script:
  - docker-compose -f docker-compose.test.yml up db &

script:
  - docker-compose -f docker-compose.test.yml up --build app
