version: '2'

services:
  app:
    build: .
    volumes:
      - ./.cabal-sandbox.docker:/app/.cabal-sandbox
    links:
      - db

  db:
    image: postgres:9.5
    volumes_from:
      - dbdata_box

  dbdata_box:
    image: busybox
    volumes:
      - /var/lib/postgresql/data

  web:
    build: ./nginx-docker
    ports:
      - "80:80"
    links:
      - app